[package]
name = "qga"
version = "0.1.0"
edition = "2018"
license = "GPLv2"

[dependencies]
common = { path = "../rust/common" }
libc = "^0.2.76"
hostname = "^0.3.1"

[lib]
path = "lib.rs"
crate-type = ["staticlib"]
