.cross_common_job:
  stage: build
  image: $CI_REGISTRY_IMAGE/qemu/$IMAGE:latest
  rules:
    # If the if statement is true, the job is added to the pipeline.
    # We only filter for push events
    - if: '$CI_PIPELINE_SOURCE != "push"'
    # Build all when no variable defined, or set to "all"
    - if: $QEMU_BUILD == null || $QEMU_BUILD =~ /^all$/
    # Build specific job name
    - if: $QEMU_BUILD =~ /^$CI_JOB_NAME$/
    # Build set of jobs by feature
    - if: $QEMU_BUILD =~ /cross/
    - if: $QEMU_BUILD =~ /system/ && $CI_JOB_NAME =~ /system/
    - if: $QEMU_BUILD =~ /user/ && $CI_JOB_NAME =~ /user/
    # Build set of jobs by arch
    - if: $QEMU_BUILD =~ /aarch64/ && ($CI_JOB_NAME =~ /aarch64/ || $IMAGE =~ /aarch64/)
    - if: $QEMU_BUILD =~ /alpha/ && ($CI_JOB_NAME =~ /alpha/ || $IMAGE =~ /alpha/)
    - if: $QEMU_BUILD =~ /arm/ && ($CI_JOB_NAME =~ /arm/ || $IMAGE =~ /arm/)
    - if: $QEMU_BUILD =~ /avr/ && ($CI_JOB_NAME =~ /avr/ || $IMAGE =~ /avr/)
    - if: $QEMU_BUILD =~ /hppa/ && ($CI_JOB_NAME =~ /hppa/ || $IMAGE =~ /hppa/)
    - if: $QEMU_BUILD =~ /i386/ && ($CI_JOB_NAME =~ /i386/ || $IMAGE =~ /i386/)
    - if: $QEMU_BUILD =~ /lm32/ && ($CI_JOB_NAME =~ /lm32/ || $IMAGE =~ /lm32/)
    - if: $QEMU_BUILD =~ /m68k/ && ($CI_JOB_NAME =~ /m68k/ || $IMAGE =~ /m68k/)
    - if: $QEMU_BUILD =~ /ppc/ && ($CI_JOB_NAME =~ /ppc/ || $IMAGE =~ /ppc/)
    - if: $QEMU_BUILD =~ /riscv/ && ($CI_JOB_NAME =~ /riscv/ || $IMAGE =~ /riscv/)
    - if: $QEMU_BUILD =~ /s390x/ && ($CI_JOB_NAME =~ /s390x/ || $IMAGE =~ /s390x/)
    - if: $QEMU_BUILD =~ /sparc/ && ($CI_JOB_NAME =~ /sparc/ || $IMAGE =~ /sparc/)
    - if: $QEMU_BUILD =~ /tricore/ && ($CI_JOB_NAME =~ /tricore/ || $IMAGE =~ /tricore/)
    - if: $QEMU_BUILD =~ /x86/ && ($CI_JOB_NAME =~ /x86/ || $IMAGE =~ /x86/)
    - if: $QEMU_BUILD =~ /xtensa/ && ($CI_JOB_NAME =~ /xtensa/ || $IMAGE =~ /xtensa/)
    # In all other cases, the job is excluded from a pipeline.
    - when: never

.cross_system_build_job:
  extends: .cross_common_job
  timeout: 80m
  script:
    - mkdir build
    - cd build
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH
      ../configure --enable-werror $QEMU_CONFIGURE_OPTS --disable-user
        --target-list-exclude="aarch64-softmmu i386-softmmu microblaze-softmmu
          mips-softmmu mipsel-softmmu mips64-softmmu ppc64-softmmu sh4-softmmu
          xtensa-softmmu"
    - make -j$(expr $(nproc) + 1) all check-build

.cross_user_build_job:
  extends: .cross_common_job
  script:
    - mkdir build
    - cd build
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH
      ../configure --enable-werror $QEMU_CONFIGURE_OPTS --disable-system
    - make -j$(expr $(nproc) + 1) all check-build

cross-armel-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-armel-cross

cross-armel-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-armel-cross

cross-armhf-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-armhf-cross

cross-armhf-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-armhf-cross

cross-arm64-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-arm64-cross

cross-arm64-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-arm64-cross

cross-mips-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-mips-cross

cross-mips-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-mips-cross

cross-mipsel-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-mipsel-cross

cross-mipsel-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-mipsel-cross

cross-mips64el-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-mips64el-cross

cross-mips64el-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-mips64el-cross

cross-ppc64el-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-ppc64el-cross

cross-ppc64el-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-ppc64el-cross

cross-s390x-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: debian-s390x-cross

cross-s390x-user:
  extends: .cross_user_build_job
  variables:
    IMAGE: debian-s390x-cross

cross-win32-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: fedora-win32-cross

cross-win64-system:
  extends: .cross_system_build_job
  variables:
    IMAGE: fedora-win64-cross
