include:
  - local: '/.gitlab-ci.d/stages.yml'
  - local: '/.gitlab-ci.d/container-core.yml'
  - local: '/.gitlab-ci.d/crossbuild-template.yml'
  - local: '/.gitlab-ci.d/checks.yml'

build-libvhost-user:
  stage: build
  image: $CI_REGISTRY_IMAGE/qemu/fedora:latest
  needs:
    job: amd64-fedora-container
  before_script:
    - dnf install -y meson ninja-build
  script:
    - mkdir subprojects/libvhost-user/build
    - cd subprojects/libvhost-user/build
    - meson
    - ninja

s390x-debian-cross-container:
  extends: .container_job_template
  stage: containers-layer2
  needs: ['amd64-debian10-container']
  variables:
    NAME: debian-s390x-cross

cross-s390x-kvm-only:
  extends: .cross_accel_build_job
  needs:
    job: s390x-debian-cross-container
  variables:
    IMAGE: debian-s390x-cross
    ACCEL_CONFIGURE_OPTS: --disable-tcg
