# -*- Mode: makefile -*-
#
# MIPS - included from tests/tcg/Makefile.target
#

MIPS_SRC=$(SRC_PATH)/tests/tcg/mips

# Set search path for all sources
VPATH 		+= $(MIPS_SRC)

# hello-mips is 32 bit only
ifeq ($(findstring 64,$(TARGET_NAME)),)
MIPS_TESTS=hello-mips
hello-mips: CFLAGS+=-mno-abicalls -fno-PIC -mabi=32
hello-mips: LDFLAGS+=-nostdlib
endif

# r5900 is only 64 bit little-endian
ifneq ($(findstring 64el,$(TARGET_NAME)),)
MIPS_TESTS += test-r5900-dmult
test-r5900-dmult: CFLAGS += -mabi=n32 -march=r5900
endif

TESTS += $(MIPS_TESTS)
